//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFmpegFarm.WindowsService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Threads {
            get {
                return ((int)(this["Threads"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\net\\ODudv\\state\\FfmpegFarm\\Logfiles")]
        public string FFmpegLogPath {
            get {
                return ((string)(this["FFmpegLogPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://od01udv.net.dr.dk:9000")]
        public string ControllerApi {
            get {
                return ((string)(this["ControllerApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FC_CONFIG_DIR=\\\\net\\ODudv\\state\\FfmpegFarm\\Tooling\\ffmpegfonts;FONTCONFIG_FILE=\\\\" +
            "net\\ODudv\\state\\FfmpegFarm\\Tooling\\ffmpegfonts\\fonts.conf;FONTCONFIG_PATH=\\\\net\\" +
            "ODudv\\state\\FfmpegFarm\\Tooling\\ffmpegfonts")]
        public string EnvorimentVars {
            get {
                return ((string)(this["EnvorimentVars"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\net\\ODudv\\state\\FfmpegFarm\\Tooling\\Ffmpeg\\ffmpeg-3.4.1-win64-static\\bin\\ffmpeg." +
            "exe")]
        public string FFmpegPath {
            get {
                return ((string)(this["FFmpegPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\net\\ODudv\\state\\FfmpegFarm\\Tooling\\stereotool\\stereo_tool_cmd_9.02.exe")]
        public string StereoToolPath {
            get {
                return ((string)(this["StereoToolPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\net\\ODudv\\state\\FfmpegFarm\\Tooling\\stereotool\\presets\\")]
        public string StereoToolPresetsPath {
            get {
                return ((string)(this["StereoToolPresetsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\net\\ODudv\\state\\FfmpegFarm\\Tooling\\stereotool\\license")]
        public string StereoToolLicensePath {
            get {
                return ((string)(this["StereoToolLicensePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Temp")]
        public string ForceTempFolder {
            get {
                return ((string)(this["ForceTempFolder"]));
            }
        }
    }
}
